#' Plots predicted tvcure object.
#'
##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param predobj An object produced by the predicttvcure function.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param ... Further options to be passed to \link{matplot}.
plot.predicttvcure <- function(predobj, type = c("basesurv", "spop", "suncure", "uncureprob"),
                               xlab = "Time", legendtitle = NULL, ylab = "Predicted Survival Probability", ...) {
  require(ggplot2)
  require(plotrix)
  CI = predobj$CI
  Time = predobj$Time
  nprof = predobj$nprof
  uncureprob = predobj$uncureprob
  s0 = predobj$s0
  suncure = predobj$suncure
  spop = predobj$spop
  variable = predobj$variable
  values <- predobj$newZ[, variable]
  # values = predobj$values

  # a <- cbind(1:nprof, t(predobj$suncure))
  # b <- rep(Time, nprof)
browser()
  if (CI == F) {
    if (type == "uncureprob")
      p1 <- plot(values, as.vector(uncureprob), ylim = c(round(min(uncureprob), 2), round(max(uncureprob), 2)), xlim = c(0, nprof-1), asp = 1, ylab = "Probability")
      axis(1, seq(0, 1, 1))
      for (i in 2:nprof) {
        points(i, uncureprob[, i])
      }
      plot(uncureprob[, 1], ylim = c(round(min(uncureprob), 2), round(max(uncureprob), 2)))
    if (type == "basesurv") {
      p1 <- plot(Time, s0, type = "l",
                 ylim = c(round(min(s0), 2), round(max(s0), 2)), ylab = ylab)
    }
      # p1 <- ggplot(mapping = aes(x = Time, y = predobj$s0)) + geom_line()
    if (type == "suncure") {
      p1 <- plot(Time, suncure[, 1], type = "l", ylim = c(round(min(suncure), 2), round(max(suncure), 2)), ylab = ylab)
      for (i in 2:nprof) {
        lines(Time, suncure[, i], type = "l", col = i)
      }
      scm  <- testpredb$suncuremean
    sclo <- testpredb$suncurelo
    schi <- testpredb$suncurehi
    scm  <- split(scm, rep(1:ncol(scm), each = nrow(scm)))
    sclo <- split(sclo, rep(1:ncol(sclo), each = nrow(sclo)))
    schi <- split(schi, rep(1:ncol(schi), each = nrow(schi)))
    for (i in 1:length(scm)) {
      scm[[i]] <- cbind(scm[[i]], Time, num = i, sclo[[i]], schi[[i]])
    }
    scf <- as.data.frame(do.call(rbind, scm))
    colnames(scf) <- c("scm", "Time", "num", "sclo", "schi")


ggplot(scf, aes(Time, scm, col = as.factor(num))) + geom_line() + geom_ribbon(aes(ymin = sclo, ymax = schi, col = as.factor(num)), alpha=0.1)

    }
    if (type == "spop") {
      p1 <- plot(Time, spop[, 1], type = "l", ylim = c(round(min(spop), 2), round(max(spop), 2)), ylab = ylab)
      for (i in 2:nprof) {
        lines(Time, spop[, i], type = "l", col = i)
      }
      legend("topright", legend = values, col = 1:nprof, lty = 1:nprof, title = legendtitle)
      # p1 <- ggplot(mapping = aes(x = predobj$Time, y = predobj$spop[, 1])) + geom_line() +
      #   geom_line(aes(x = Time, y = spop[,  6 ]) +
      #   geom_line(aes(x = Time, y = spop[,  7 ])))
      #  #p2 <- ggplot(mapping = aes(x = predobj$Time, y = predobj$spop[, 2])) + geom_line()
      #         # p2 <- geom_line(aes(x = predobj$Time, y = predobj$spop[, 2]))
      #   # p3 <- geom_line(aes(x = predobj$Time, y = predobj$spop[, 3]))
      #
      # for(j in 2:nprof) {
      #   assign(paste("p", j, sep = ""), geom_line(aes(x = Time, y = spop[, j])))
      #   a <- paste("geom_line(aes(x = Time, y = spop[, ", j, "])")
      #   b <- paste("geom_line(aes(x = Time, y = spop[, ", j, "])")
      #   p1 +
      #   paste(pi)
    }
  }
  p1
}

# Legends
