#https://stat.ethz.ch/pipermail/r-help//2013-January/344429.html
#' Predict
#' ##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param model A model of class tvcure.
#' @param variable Variable to produce predictions for
#' @param CI Logical value indicating whether predictions and confidence intervals should be estimated using maximum simulated likelihood
#' @param nsims The number of simulated coefficient valeus to estimate when computing confidence intervals.
#' @param Logical value indicating whether graphs should be printed in black and white.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param internals A logical value indicating whether the predictions should be returned. If FALSE, only the graph will be returned.

prediction4 <- function(model, variable = NULL, values = NULL, newX = NULL, newZ = NULL,
                        type = c("basesurv", "spop", "suncure", "uncureprob"),
                        CI = T, nsims = 1000, bw = F,
                        xlab = "Time", legendtitle = NULL,
                        ylab = "Predicted Survival Probability", internals = F) {



  # Create dataset for predictions -----------------------------------------------------------


 else { ## With CIs =========================================================================

    Coef_smplb <- MASS::mvrnorm(n = nsims, mu = beta, Sigma = vcovb)
    Coef_smplg <- MASS::mvrnorm(n = nsims, mu = gamma, Sigma =  vcovg)

    # Estimate nsims simulated values of uncureprob
    if (link == "logit") {
      uncureprobsims <- exp(Coef_smplg %*% t(newZ)) / (1 + exp(Coef_smplg %*% t(newZ)))
    }
    if (link == "probit") {
      uncureprobsims <- pnorm(Coef_smplg %*% t(newZ))
    }
    uncuremean = apply(uncureprobsims, 2, mean)
    uncurelo   = apply(uncureprobsims, 2, quantile, 0.05)
    uncurehi   = apply(uncureprobsims, 2, quantile, 0.95)

    # Simulate baseline hazard
    s0sim <- matrix(nrow = nsims, ncol = nobs)
    for (j in 1:nsims) {
      s0sim[j, ] <- as.vector(s0)^exp(Coef_smplb[j, ] %*% t(model$X))
    }
    s0mean <- sort(apply(s0sim, 2, mean), decreasing = T)
    s0lo   <- sort(apply(s0sim, 2, quantile, 0.05), decreasing = T)
    s0hi   <- sort(apply(s0sim, 2, quantile, 0.95), decreasing = T)

    # Obtain simulated values of suncure and spop
    ebetaXsim <- exp(Coef_smplb %*% t(newX))
    suncuresims <- array(NA, dim = c(nsims, nobs, nrow(newX)))
    spopsims    <- array(NA, dim = c(nsims, nobs, nrow(newX)))

    if (type == "suncure" | type == "spop") {
      for (i in 1:nsims) {
        for (k in 1:nrow(newX)) {
          suncuresims[i, , k] <- s0sim[i, ]^ebetaXsim[i, k]
          spopsims[i, , k] <- uncureprobsims[i, k] *
            suncuresims[i, , k] + (1 - uncureprobsims[i, k])
        }
      }
    }


    suncuremean <- matrix(nrow = nobs, ncol = dim(newZ))
    suncurelo   <- matrix(nrow = nobs, ncol = dim(newZ))
    suncurehi   <- matrix(nrow = nobs, ncol = dim(newZ))
    spopmean    <- matrix(nrow = nobs, ncol = dim(newZ))
    spoplo      <- matrix(nrow = nobs, ncol = dim(newZ))
    spophi      <- matrix(nrow = nobs, ncol = dim(newZ))

    for (k in 1:nrow(newX)) {
      if (type == "suncure") {
        suncuremean[, k] <- sort(apply(suncuresims[, , k], 2, mean), decreasing = T)
        suncurelo[, k]   <- sort(apply(suncuresims[, , k], 2, quantile, 0.05), decreasing = T)
        suncurehi[, k]   <- sort(apply(suncuresims[, , k], 2, quantile, 0.95), decreasing = T)
      }
      if (type == "spop") {
        spopmean[, k]    <- sort(apply(spopsims[, , k], 2, mean), decreasing = T)
        spoplo[, k]      <- sort(apply(spopsims[, , k], 2, quantile, 0.05), decreasing = T)
        spophi[, k]      <- sort(apply(spopsims[, , k], 2, quantile, 0.95), decreasing = T)
      }
    }
  } # close CI = T else loop

  # Output ------------------------------------------------------------------
      structure(list(uncuremean = uncuremean, uncurelo = uncurelo, uncurehi = uncurehi,
                     s0mean = s0mean, s0lo = s0lo, s0hi = s0hi,
                     suncuremean, suncurelo, suncurehi,
                     Survival = model$Survival,
                     spopmean = spopmean, spoplo = spoplo, spophi = spophi,
                     link = link, Time = Time, CI = CI,
                     newX = newX, newz = newZ, variable = variable, splot = splot),
                class = "predicttvcure")
    }
  }
}
