**Load thrower_ajps_replication_main.dta Stata dta file (Stata 14 version used)

****************************Main Analysis in Paper*******************************
***Table 1: Cox Proporitional Hazards Model - Baseline Model***
stcox divdgovt fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_inflation  current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust
stcox divdgovt recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_presapprove current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
	
***Table 2: Cox Proportional Hazards Model - Interaction Model***
stcox i.recent##c.pres_dist if year > 1948 & ceremonial==0, nohr robust
stcox i.recent##c.pres_dist issuing_pcong_dist fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust

***Figure 3: The Conditional Hypothesis Interaction***
stcox i.recent##c.pres_dist if year > 1948 & ceremonial==0, nohr robust
margins, dydx(pres_dist) at(recent==(0 1)) level(95)
marginsplot, yline(0)

***Figure 2: Hazard Function***
stcox divdgovt fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_inflation  current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust
stcurve, hazard
*********************************************************************************


************************Analyses in Supplemental Materials***********************

***Table A2: Summary Statistics***
sum divdgovt issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend37 current_divdgovt current_pcong_dist current_presapprove current_inflation  current_electyr opposing_pres pres_dist log_eo_total current_admchg current_endterm current_war current_trend37, detail

***Table B1: Foreign Policy Interaction***
stcox i.fds##c.pres_dist if ceremonial==0, nohr robust
stcox i.fds##c.pres_dist issuing_pcong_dist nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation current_electyr log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust

***Table B2: Temporary Functions and Emergency EOs***
stcox temporaryandemergencyfunctions issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0 & temporaryandemergencyfunctions==0, nohr robust

***Table B3: Continuing Policy Areas***
stcox committee civilservice civilrights intelligence nationalsecurity foreignservice militaryoperations governmentcontracting publicland issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0 & committee==0 & civilservice==0 & civilrights==0 & intelligence==0 & nationalsecurity==0 & foreignservice==0 & militaryoperations==0 & governmentcontracting==0 & publicland==0, nohr robust

***Table B4: Not Including Reagan EO 12553***
stcox divdgovt recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm  trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_presapprove current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0 & revokedbyeo12553==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0 & revokedbyeo12553==0, nohr robust

****Table B7: Pre and Post 1969****
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 if ceremonial==0 & year < 1969, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 if year > 1948 & year < 1969 & ceremonial==0, nohr robust
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend69 Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend69 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0 & year > 1968, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend69 Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend69 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1968 & ceremonial==0, nohr robust

****Table B8: Pre and Post 1981****
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 if ceremonial==0 & year < 1981, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2  if year > 1948 & year < 1981 & ceremonial==0, nohr robust
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend81 Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend81 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0 & year > 1980, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend81 Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend81 Bush412 Clinton2 Bush432 Obama2 if year > 1980 & ceremonial==0, nohr robust
	
***Table B9: Nonproportional Hazard Models***
stcox divdgovt fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 y_div1 y_adm1 y_end1 y_elect1 y_war1 y_infl1 y_pub y_trend1a y_truman y_lbj y_bush43 y_opp2 y_eo2 y_adm2 y_end2 y_war2 y_infl2 y_elect2 y_trend2a y_truman2 y_ike2 y_jfk2 y_lbj2 y_nix2 y_ford2 y_carter2 y_reagan2 y_bush412 y_clinton2 y_bush432 y_obama2 if ceremonial==0, nohr robust
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412  Clinton2  Bush432 Obama2 y_adm1 y_end1 y_elect1 y_war1 y_infl1 y_fds y_pub y_trend1a y_truman y_ike y_jfk y_lbj y_nix y_bush41 y_clinton y_bush43 y_obama y_pcong2 y_pdist y_eo2 y_adm2 y_end2 y_war2 y_infl2 y_elect2 y_trend2a y_truman2 y_ike2 y_jfk2 y_lbj2 y_nix2 y_ford2 y_carter2 y_reagan2  y_bush412 y_clinton2 y_bush432 y_obama2 if ceremonial==0, nohr robust
stcox divdgovt recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_presapprove current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2  Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2  Bush432 Obama2 y_div1 y_words y_adm1 y_end1 y_elect1 y_war1 y_infl1 y_fds y_nyt y_pub y_trend1b y_ike y_lbj y_clinton y_bush43  y_obama y_div2 y_opp2 y_eo2 y_adm2 y_end2 y_war2 y_infl2 y_elect2 y_trend2b y_ike2 y_lbj2 y_ford2 y_bush412 y_clinton2 y_bush432 y_obama2 if ceremonial==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 y_pcong1 y_end1 y_elect1 y_war1 y_fds y_nyt y_pub y_trend1b y_lbj y_nix y_bush41 y_clinton y_bush43 y_obama y_pcong2 y_pdist y_eo2 y_approve2 y_end2 y_war2 y_infl2 y_elect2 y_trend2b y_ike2 y_jfk2 y_lbj2 y_nix2 y_ford2 y_carter2 y_reagan2 y_bush412 y_clinton2 y_bush432 y_obama2 if ceremonial==0, nohr robust

***Table B10: Multinomial Probit Model***
mprobit all_cats issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, robust

***Table B5: Excluding Partial Revoke***
*Load thrower_ajps_replication_tableb5.dta
	
stcox divdgovt fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_inflation  current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust
stcox issuing_pcong_dist fds nyt public_mention war inflation electyr admchg endterm trend37 Truman IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_inflation  current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend37 Truman2 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if ceremonial==0, nohr robust
stcox divdgovt recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_presapprove current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust 
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust

***Table B6: Excluding EOs that Amend Revoked Orders***
*Load thrower_ajps_replication_tableb6.dta

stcox divdgovt recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_divdgovt current_presapprove current_inflation current_electyr opposing_pres log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
stcox issuing_pcong_dist recent fds nyt public_mention log_words war inflation presapprove_year electyr admchg endterm trend49 IKE JFK LBJ Nixon Ford Carter Reagan Bush41 Clinton Bush43 Obama current_pcong_dist current_presapprove current_inflation current_electyr pres_dist log_eo_total current_admchg current_endterm current_war current_trend49 IKE2 JFK2 LBJ2 Nixon2 Ford2 Carter2 Reagan2 Bush412 Clinton2 Bush432 Obama2 if year > 1948 & ceremonial==0, nohr robust
*********************************************************************************
