#' Plots predicted tvcure object.
#'
##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param predobj An object produced by the predicttvcure function.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param ... Further options to be passed to \link{matplot}.
plot.predicttvcure <- function(predobj, type = c("basesurv", "spop", "suncure"), xlab = "Time", ylab = "Predicted Survival Probability", ...) {
  #model <- predobj$model
  if (type == "basesurv") pred <- predobj$sbase
  if (type == "spop")     pred <- predobj$spop
  if (type == "suncure")  pred <- predobj$suncure
  Time <- predobj$Time
  mat <- cbind(pred)
  #if (model == "ph") {

  pdsort <- mat[order(Time), ]
  matplot(Time, pdsort[, "Time"], pdsort[, -(ncol(pdsort))], type = "l",
          lty = 1:(ncol(pred)), xlab = xlab, ylab = ylab, ...)
  #}
  # if (model == "aft") {
  #   nplot = ncol(pred)/2
  #   pdsort <- pred[order(pred[, 1 + nplot]), c(1, 1 + nplot)]
  #   plot(pdsort[, 2], pdsort[, 1], xlab = xlab, ylab = ylab,
  #        col = 1, type = "S", ylim = c(0, 1))
  #   if (nplot > 1) {
  #     for (i in 2:nplot) {
  #       pdsort <- pred[order(pred[, i + nplot]), c(i, i + nplot)]
  #       lines(pdsort[, 2], pdsort[, 1], lty = i, type = "S")
  #     }
  #   }
  # }
}
