#https://stat.ethz.ch/pipermail/r-help//2013-January/344429.html
#' Predict
#' ##' Plots predicted survival curves from objects generated by the predicttvcure function.
#' @param model A model of class tvcure.
#' @param variable A character string
#' @param CI Logical value indicating whether predictions and confidence intervals should be estimated using maximum simulated likelihood
#' @param nsims The number of simulated coefficient values to estimate when computing confidence intervals.
#' @param Logical value indicating whether graphs should be printed in black and white.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param internals A logical value indicating whether the predictions should be returned. If FALSE, only the graph will be returned.

plotsurv = function(object, type = c("basesurv", "suncure", "spop"),
                     legendtitle = NULL, ylab = "Survival Probability", xlab = "Time") {

  # Setup -------------------------------------------------------------------

  require(ggplot2)
  type = match.arg(type)
  failtime = object$failtime
  CI = F

  # Plot Setup --------------------------------------------------------------
  splot = ggplot() + theme_bw()

  # Uncureprob Plot ---------------------------------------------------------
  if (type == "uncureprob") {
    if (CI == F) {
      splot = ggplot(mapping = aes(x = values, y = as.vector(uncureprob))) + geom_point()
    } else {
      splot = ggplot(mapping = aes(x = values, y = as.vector(uncuremean))) + geom_point() +
        geom_errorbar(width = (length(values)/10),
                      mapping = aes(x = values, ymin = uncurelo, ymax = uncurehi),
                      colour = "black")
    }
    splot = splot + scale_x_continuous(breaks = values) + theme(legend.position = "none") + theme_bw()
  }

  # Basesurv Plot -----------------------------------------------------------

  if (type == "basesurv") {
    # if (CI == F) {
      splot = splot + geom_step(mapping = aes(failtime, object$basesurv), size = .75)
    # } else {
    #   splot = splot + geom_step(mapping = aes(failtime, s0mean), size = .75) +
    #     geom_ribbon(aes(x = failtime, ymin = s0lo, ymax = s0hi), alpha=0.2)
    # }
    splot = splot + ylab(ylab) + xlab(failtime)
  }

  # Suncure Plot ------------------------------------------------------------
  if (type == "suncure") {

    # Structure data
    # if (CI == F) {
      suncure = as.matrix(object$suncure)
      scm  = split(suncure, rep(1:ncol(suncure), each = nrow(suncure)))
      for (i in 1:length(scm)) {
        scm[[i]] = cbind(scm[[i]], failtime, num = i)
      }
      scf = as.data.frame(do.call(rbind, scm))
      colnames(scf) = c("scm", "failtime", "num")
    # } else {
    #   scm  = split(suncuremean, rep(1:ncol(suncuremean), each = nrow(suncuremean)))
    #   sclo = split(suncurelo, rep(1:ncol(suncurelo), each = nrow(suncurelo)))
    #   schi = split(suncurehi, rep(1:ncol(suncurehi), each = nrow(suncurehi)))
    #   for (i in 1:length(scm)) {
    #     scm[[i]] = cbind(scm[[i]], failtime, num = i, sclo[[i]], schi[[i]])
    #   }
    #   scf = as.data.frame(do.call(rbind, scm))
    #   colnames(scf) = c("scm", "failtime", "num", "sclo", "schi")
    # }

    # Plot line
    splot = splot + geom_step(scf,
                              mapping = aes(failtime, scm,
                                            col = as.factor(num),
                                            linetype = as.factor(num)),
                              size = .75)
    #+ labs(linetype = legendtitle, col = legendtitle)

    # # Add CIs
    # if (CI == T) {
    #   if (bw == F) {
    #     splot = splot + geom_ribbon(scf, mapping = aes(x = failtime,
    #                                                    ymin = sclo, ymax = schi,
    #                                                    col = as.factor(num),
    #                                                    fill = as.factor(num),
    #                                                    linetype = as.factor(num)), alpha=0.2) +
    #       labs(fill = legendtitle, linetype = legendtitle, col = legendtitle)
    #   } else {
    #     splot = splot + geom_ribbon(scf, mapping = aes(x = failtime, ymin = sclo, ymax = schi,
    #                                                    linetype = as.factor(num)), alpha=0.2) +
    #       labs(linetype = legendtitle)
    #   }
    # }
  }

  # Spop Plot ---------------------------------------------------------------
  if (type == "spop") {
    # vals = round(values, 1)
    # Structure data
    # if (CI == F) {
      spop = as.matrix(object$spop)
      spm  = split(spop, rep(1:ncol(spop), each = nrow(spop)))
      for (i in 1:length(spm)) {
        spm[[i]] = cbind(spm[[i]], failtime, num = i)
      }
      spf = as.data.frame(do.call(rbind, spm))
      colnames(spf) = c("spm", "failtime", "num")
    # } else {
    #   spm  = split(spopmean, rep(1:ncol(spopmean), each = nrow(spopmean))) # two matrices of simulated spops
    #   splo = split(spoplo, rep(1:ncol(spoplo), each = nrow(spoplo)))
    #   sphi = split(spophi, rep(1:ncol(spophi), each = nrow(spophi)))
    #   for (i in 1:length(spm)) {
    #     spm[[i]] = cbind(spm[[i]], failtime, num = i, splo[[i]], sphi[[i]])
    #   }
    #   spf = as.data.frame(do.call(rbind, spm))
    #   colnames(spf) = c("spm", "failtime", "num", "splo", "sphi")
    # }

    # Plot line
    splot = splot + geom_step(spf, mapping = aes(failtime, spm,
                                                 col = as.factor(num),
                                                 linetype = as.factor(num)),
                              size = .75)
    # +labs(linetype = legendtitle, col = legendtitle, fill = legendtitle)

    # splot + scale_fill_discrete(labels = vals)

    # # Add CIs
    # if (CI == T) {
    #   if (bw == F) {
    #     splot = splot + geom_ribbon(spf, mapping = aes(x = failtime, ymin = splo, ymax = sphi,
    #                                                    col = as.factor(num),
    #                                                    fill = as.factor(num),
    #                                                    linetype = as.factor(num)), alpha = 0.2)# +
    #     labs(fill = legendtitle, linetype = legendtitle, col = legendtitle)
    #   } else {
    #     splot = splot + geom_ribbon(spf, mapping = aes(x = failtime, ymin = splo, ymax = sphi,
    #                                                    linetype = as.factor(num)), alpha = 0.2) +
    #       labs(linetype = legendtitle)
    #   }
    # }
    # splot = splot + ylab(ylab) + xlab(xlab) +
    #   scale_linetype_discrete(labels = vals)  +
    #   scale_color_discrete(labels = vals) +
    #   scale_fill_discrete(labels = vals)
  }

  # Return --------------------------------------------------------------------
  splot = splot + ylab(ylab) + xlab(xlab)
  splot
}
