#' Plots predicted tvcure object.
#'
##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param Object An object produced by the predicttvcure function.
#' @param basesurv If true, plots the baseline hazard function as the first curve.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param model Model type: either "ph" or "aft".
#' @param ... Further options to be passed to \link{matplot}.
plot_predict_tvcure <- function(object, basesurv = F, xlab = "Time",
                               ylab = "Predicted Survival Probability", ...) {
  if (basesurv) pred <- cbind(object$s0, object$prediction)
  else pred <- object$prediction
  #if (model == "ph") {
    pdsort <- pred[order(pred[, "Time"]), ]
      matplot(pdsort[, "Time"], pdsort[, 1:(ncol(pred) -1)], type = "S",
              lty = 1:(ncol(pred) - 1), xlab = xlab, ylab = ylab, ...)
  #}
  # if (model == "aft") {
  #   nplot = ncol(pred)/2
  #   pdsort <- pred[order(pred[, 1 + nplot]), c(1, 1 + nplot)]
  #   plot(pdsort[, 2], pdsort[, 1], xlab = xlab, ylab = ylab,
  #        col = 1, type = "S", ylim = c(0, 1))
  #   if (nplot > 1) {
  #     for (i in 2:nplot) {
  #       pdsort <- pred[order(pred[, i + nplot]), c(i, i + nplot)]
  #       lines(pdsort[, 2], pdsort[, 1], lty = i, type = "S")
  #     }
  #   }
  # }
}
