#' Predict
#' ##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param model A model of class tvcure.
#' @param variable Variable to produce predictions for
#' @param CI Logical value indicating whether predictions and confidence intervals should be estimated using maximum simulated likelihood
#' @param nsims The number of simulated coefficient valeus to estimate when computing confidence intervals.
#' @param Logical value indicating whether graphs should be printed in black and white.
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.
#' @param internals A logical value indicating whether the predictions should be returned. If FALSE, only the graph will be returned.

prediction2 <- function(model, variable, values,
                        type = c("basesurv", "spop", "suncure", "uncureprob"),
                        CI = NULL, nsims = 1000, bw = F,
                        xlab = "Time", legendtitle = NULL,
                        ylab = "Predicted Survival Probability", internals = F) {

# Setup -------------------------------------------------------------------

  require(ggplot2)
  call <- match.call()
  if (!inherits(model, "tvcure")) stop("Model must be a tvcure object")
  s0 = as.matrix(model$Survival, ncol = 1)
  nobs = nrow(s0)
  beta <- model$beta
  gamma <- model$gamma
  bnames <- model$bnames
  gnames <- model$gnames
  link <- model$link
  Status <- model$Status
  Time <- model$Time[order(model$Time)]
  X <- model$X
  Z <- model$Z
  if (is.null(legendtitle)) {
    legendtitle <- variable
  }
  type = match.arg(type)
  # clstatus <- foreach::getDoParRegistered()
  # if (foreach::getDoParRegistered() == T) cl <- foreach::getDoSeqName()
  # if (foreach::getDoParRegistered() == F)
  cl <- foreach::registerDoSEQ()
  pb <- txtProgressBar(max = nsims, style = 3)
  progress <- function(n) setTxtProgressBar(pb, n)
  opts <- list(progress = progress)

# Create dataset for predictions -----------------------------------------------------------

  newX <- apply(X, 2, median)
  newX <- matrix(rep(newX, length(values)), ncol = length(newX), byrow = T)
  colnames(newX) <- bnames
  if (variable %in% bnames) newX[, variable] <- values
  newX <- as.matrix(newX)
  nx <- nrow(newX)

  newZ <- apply(Z, 2, median)
  newZ <- matrix(rep(newZ, length(values)), ncol = length(newZ), byrow = T)
  colnames(newZ) <- gnames
  if (variable %in% gnames) newZ[, variable] <- values
  newZ <- as.matrix(newZ)
  nz <- nrow(newZ)

# Create predictions ------------------------------------------------------------------
  # Without CIs
  if (CI == F) {
    if (link == "logit") {
      uncureprob <- exp(gamma %*% t(newZ)) / (1 + exp(gamma %*% t(newZ)))
    }
    if (link == "probit") {
      uncureprob <- pnorm(gamma %*% t(newZ))
    }

    suncure = array(0, dim = c(nobs, nx))
    ebetaX = exp(model$beta %*% t(newX))
    for (i in 1:nx) {
      suncure[, i] = s0^ebetaX[i]
    }

    spop = array(0, dim = c(nobs, nrow(newX)))
    for (i in 1:nobs) {
      for (j in 1:nrow(newX)) {
        spop[i, j] = uncureprob[j] * suncure[i, j] + (1 - uncureprob[j])
      }
    }
    s0      <- s0[order(s0, decreasing = T)]
    suncure <- suncure[order(suncure[, 1], decreasing = T), ]
    spop    <- spop[order(spop[, 1], decreasing = T), ]
  } else { ## With CIs =========================================================================
      mu = c(beta, gamma)
      Coef_smpl <- MASS::mvrnorm(n = nsims, mu = mu, Sigma = cov(diag(mu)))
      Coef_smplb <- Coef_smpl[, 1:length(beta)]
      Coef_smplg <- Coef_smpl[, (length(beta) + 1):ncol(Coef_smpl)]

      # Estimate nsims simulated values of uncureprob
      if (link == "logit") {
        uncureprobsims <- exp(Coef_smplg %*% t(newZ)) / (1 + exp(Coef_smplg %*% t(newZ)))
      }
      if (link == "probit") {
        uncureprobsims <- pnorm(Coef_smplg %*% t(newZ))
      }
      uncuremean = apply(uncureprobsims, 2, mean)
      uncurelo   = apply(uncureprobsims, 2, quantile, 0.05)
      uncurehi   = apply(uncureprobsims, 2, quantile, 0.95)

      # Simulate baseline hazard
      s0sim <- matrix(nrow = nsims, ncol = nobs)
      for (j in 1:nsims) {
        s0sim[j, ] <- as.vector(s0)^exp(Coef_smplb[j, ] %*% t(model$X))
      }
      s0mean <- sort(apply(s0sim, 2, mean), decreasing = T)
      s0lo   <- sort(apply(s0sim, 2, quantile, 0.05), decreasing = T)
      s0hi   <- sort(apply(s0sim, 2, quantile, 0.95), decreasing = T)

      # Obtain simulated values of suncure and spop
      ebetaXsim <- exp(Coef_smplb %*% t(newX))
      suncuresims <- array(NA, dim = c(nsims, nobs, nrow(newX)))
      spopsims    <- array(NA, dim = c(nsims, nobs, nrow(newX)))

      if (type == "suncure" | type == "spop") {
        foreach (i = 1:nsims, .options.snow = opts, .errorhandling = 'remove') %:%
        		foreach (k = 1:nrow(newX)) %dopar% {
        			suncuresims[i, , k] <- s0sim[i, ]^ebetaXsim[i, k]
        		  spopsims[i, , k] <- uncureprobsims[i, k] *
        		      suncuresims[i, , k] + (1 - uncureprobsims[i, k])
        		  }
      }

      suncuremean <- matrix(nrow = nobs, ncol = dim(newZ))
      suncurelo   <- matrix(nrow = nobs, ncol = dim(newZ))
      suncurehi   <- matrix(nrow = nobs, ncol = dim(newZ))
      spopmean    <- matrix(nrow = nobs, ncol = dim(newZ))
      spoplo      <- matrix(nrow = nobs, ncol = dim(newZ))
      spophi      <- matrix(nrow = nobs, ncol = dim(newZ))

      foreach(i = 1:nsims, .options.snow = opts, .errorhandling = 'remove') %dopar% {
        #for (k in 1:nrow(newX)) {
        if (type == "suncure") {
          suncuremean[, i] <- sort(apply(suncuresims[, , i], 2, mean), decreasing = T)
          suncurelo[, i]   <- sort(apply(suncuresims[, , i], 2, quantile, 0.05), decreasing = T)
          suncurehi[, i]   <- sort(apply(suncuresims[, , i], 2, quantile, 0.95), decreasing = T)
        }
        if (type == "spop") {
          spopmean[, i]    <- sort(apply(spopsims[, , i], 2, mean), decreasing = T)
          spoplo[, i]      <- sort(apply(spopsims[, , i], 2, quantile, 0.05), decreasing = T)
          spophi[, i]      <- sort(apply(spopsims[, , i], 2, quantile, 0.95), decreasing = T)
        }
      }
    } # close CI = T else loop

# Plot Setup --------------------------------------------------------------
  if (bw == T) {
    splot <- ggplot() + theme_bw()
  } else {
    splot <- ggplot() + theme(panel.border = element_rect(colour = "black", fill = NA))
  }

# Uncureprob Plot ---------------------------------------------------------
  if (type == "uncureprob") {
    if (CI == F) {
      splot <- ggplot(mapping = aes(x = values, y = as.vector(uncureprob))) + geom_point()
    } else {
      splot <- ggplot(mapping = aes(x = values, y = as.vector(uncuremean))) + geom_point() +
        geom_errorbar(width = (length(values)/10), mapping = aes(x = values, ymin = uncurelo, ymax = uncurehi), colour = "black")
    }
    splot <- splot + scale_x_continuous(breaks = values) + ylab("Probability of Failure") +
      xlab(variable) + theme(legend.position = "none") + theme_bw()
  }

# Basesurv Plot -----------------------------------------------------------

  if (type == "basesurv") {
    if (CI == F) {
      splot <- splot + geom_line(mapping = aes(Time, s0))
    } else {
      splot <- splot + geom_line(mapping = aes(Time, s0mean)) +
        geom_ribbon(aes(x = Time, ymin = s0lo, ymax = s0hi), alpha=0.2)
    }
    splot = splot + ylab(ylab) + xlab(variable)# +
  }

# Suncure Plot ------------------------------------------------------------
  if (type == "suncure") {

    # Structure data
    if (CI == F) {
      scm  <- split(suncure, rep(1:ncol(suncure), each = nrow(suncure)))
      for (i in 1:length(scm)) {
        scm[[i]] <- cbind(scm[[i]], Time, num = i)
      }
      scf <- as.data.frame(do.call(rbind, scm))
      colnames(scf) <- c("scm", "Time", "num")
    } else {
      scm  <- split(suncuremean, rep(1:ncol(suncuremean), each = nrow(suncuremean)))
      sclo <- split(suncurelo, rep(1:ncol(suncurelo), each = nrow(suncurelo)))
      schi <- split(suncurehi, rep(1:ncol(suncurehi), each = nrow(suncurehi)))
      for (i in 1:length(scm)) {
        scm[[i]] <- cbind(scm[[i]], Time, num = i, sclo[[i]], schi[[i]])
      }
      scf <- as.data.frame(do.call(rbind, scm))
      colnames(scf) <- c("scm", "Time", "num", "sclo", "schi")
    }

    # Plot line
    if (bw == F) {
      splot = splot + geom_line(scf, mapping = aes(Time, scm, col = as.factor(num),
                                                   linetype = as.factor(num))) +
        labs(linetype = legendtitle, col = legendtitle)
    } else {
      splot = splot + geom_line(scf, mapping = aes(Time, scm, linetype = as.factor(num))) +
        labs(linetype = legendtitle)
    }

    # Add CIs
    if (CI == T) {
      if (bw == F) {
        splot = splot + geom_ribbon(scf, mapping = aes(x = Time, ymin = sclo, ymax = schi, col = as.factor(num),
                                    fill = as.factor(num), linetype = as.factor(num)), alpha=0.2) +
          labs(fill = legendtitle, linetype = legendtitle, col = legendtitle)
      } else {
        splot = splot + geom_ribbon(scf, mapping = aes(x = Time, ymin = sclo, ymax = schi,
                                                  linetype = as.factor(num)), alpha=0.2) +
          labs(linetype = legendtitle)
      }
    }
    splot = splot + ylab(ylab) + xlab(xlab)
  }

# Spop Plot ---------------------------------------------------------------

    # Structure data
    if (type == "spop") {

    # Structure data
    if (CI == F) {
      spm  <- split(spop, rep(1:ncol(spop), each = nrow(spop)))
      for (i in 1:length(spm)) {
        spm[[i]] <- cbind(spm[[i]], Time, num = i)
      }
      spf <- as.data.frame(do.call(rbind, spm))
      colnames(spf) <- c("spm", "Time", "num")
    } else {
      spm  <- split(spopmean, rep(1:ncol(spopmean), each = nrow(spopmean)))
      splo <- split(spoplo, rep(1:ncol(spoplo), each = nrow(spoplo)))
      sphi <- split(spophi, rep(1:ncol(spophi), each = nrow(spophi)))
      for (i in 1:length(spm)) {
        spm[[i]] <- cbind(spm[[i]], Time, num = i, splo[[i]], sphi[[i]])
      }
      spf <- as.data.frame(do.call(rbind, spm))
      colnames(spf) <- c("spm", "Time", "num", "splo", "sphi")
    }

    # Plot line
    if (bw == F) {
      splot = splot + geom_line(spf, mapping = aes(Time, spm, col = as.factor(num),                                              linetype = as.factor(num))) + labs(linetype = legendtitle, col = legendtitle)
    } else {
      splot = splot + geom_line(spf, mapping = aes(Time, spm, linetype = as.factor(num))) +
        labs(linetype = legendtitle)
    }

    # Add CIs
    if (CI == T) {
      if (bw == F) {
        splot = splot + geom_ribbon(spf, mapping = aes(x = Time, ymin = splo, ymax = sphi, col = as.factor(num),
                                    fill = as.factor(num), linetype = as.factor(num)), alpha = 0.2) +
          labs(fill = legendtitle, linetype = legendtitle, col = legendtitle)
      } else {
        splot = splot + geom_ribbon(spf, mapping = aes(x = Time, ymin = splo, ymax = sphi,
                                                  linetype = as.factor(num)), alpha = 0.2) +
          labs(linetype = legendtitle)
      }
    }
    splot = splot + ylab(ylab) + xlab(xlab)
  }

# Output ------------------------------------------------------------------
  if (internals == F) {
    return(splot)
  } else {
    if (CI == F) {
      structure(list(uncureprob = uncureprob,
                     s0 = s0, suncure = suncure, spop = spop,
                     Survival = model$Survival,
                     link = link, Time = Time, CI = CI,
                     newX = newX, newZ = newZ, variable = variable, splot = splot),
                class = "predicttvcure")

    } else {
      structure(list(uncuremean = uncuremean, uncurelo = uncurelo, uncurehi = uncurehi,
                     s0mean = s0mean, s0lo = s0lo, s0hi = s0hi,
                     suncuremean, suncurelo, suncurehi,
                     Survival = model$Survival,
                     spopmean = spopmean, spoplo = spoplo, spophi = spophi,
                     link = link, Time = Time, CI = CI,
                     newX = newX, newz = newZ, variable = variable, splot = splot),
                class = "predicttvcure")
    }
  }
}

