#' Predict
#' ##' Plots predicted surival curves from objects generated by the predicttvcure function.
#' @param model Model returned from tvcure function.
#' @param variable Variable to produce predictions for
#' @param CI Logical value indicating whether predictions and confidence intervals should be estimated using maximum simulated likelihood
#' @param nsims
#' @param xlab A label for the x-axis.
#' @param ylab A label for the y-axis.

prediction2 <- function(model, variable, values, type = c("basesurv", "spop", "suncure", "uncureprob"), CI = F, nsims = 1000,
                        xlab = "Time", legendtitle = NULL, ylab = "Predicted Survival Probability", lty = 2) {

  call <- match.call()
  if (!inherits(model, "tvcure"))
    stop("Model must be a tvcure object")
  s0 = as.matrix(model$Survival, ncol = 1)
  nobs = nrow(s0)
  beta <- model$beta
  gamma <- model$gamma
  bnames <- model$bnames
  gnames <- model$gnames
  link <- model$link
  Status <- model$Status
  Time <- model$Time[order(model$Time)]
  X <- model$X
  Z <- model$Z
  if (is.null(legendtitle)) legendtitle <- variable

  newX <- apply(X[, 2:ncol(X)], 2, median)
  newX <- matrix(rep(newX, length(values)), ncol = length(newX), byrow = T)
  colnames(newX) <- bnames
  if (variable %in% bnames) newX[, variable] <- values
  newX <- as.matrix(newX)
  nx <- nrow(newX)

  newZ <- apply(Z, 2, median)
  newZ <- matrix(rep(newZ, length(values)), ncol = length(newZ), byrow = T)
  colnames(newZ) <- gnames
  if (variable %in% gnames) newZ[, variable] <- values
  newZ <- as.matrix(newZ)
  nz <- nrow(newZ)

  if (CI == F) {
    if (link == "logit") {
      uncureprob <- exp(gamma %*% t(newZ)) / (1 + exp(gamma %*% t(newZ)))
    }
    if (link == "probit") {
      uncureprob <- pnorm(gamma %*% t(newZ))
    }

    suncure = array(0, dim = c(nobs, nx))
    ebetaX = exp(model$beta %*% t(newX))
    for (i in 1:nx) {
      suncure[, i] = s0^ebetaX[i]
    }

    spop = array(0, dim = c(nobs, nrow(newX)))
    for (i in 1:nobs) {
      for (j in 1:nrow(newX)) {
        spop[i, j] = uncureprob[j] * suncure[i, j] + (1 - uncureprob[j])
      }
    }
    s0      <- s0[order(s0, decreasing = T)]
    suncure <- suncure[order(suncure[, 1], decreasing = T), ]
    spop    <- spop[order(spop[, 1], decreasing = T), ]

    # if (type == "uncureprob") {
    #   p1 <- plot(values, as.vector(uncureprob),
    #              ylim = c(round(min(uncureprob), 2), round(max(uncureprob), 2)),
    #              xlim = c(0, nx - 1), ylab = "Probability of Failure", axes = F)
    #   box()
    #   axis(1, seq(0, 1, 1))
    #   axis(2, seq(round(min(uncureprob), 2), round(max(uncureprob), 2),
    #               by = ((round(max(uncureprob), 2) - round(min(uncureprob), 2))/2)))
    # }
    if (type == "basesurv") {
    #   # p1 <- plot(Time, s0, type = "l",
    #   #            ylim = c(round(min(s0), 2), round(max(s0), 2)), ylab = ylab)
      splot <- ggplot(mapping = aes(Time, s0)) + geom_line() +  ylab(ylab)
    }
    # if (type == "suncure") {
    #   p1 <- plot(Time, suncure[, 1], type = "l", ylim = c(round(min(suncure), 2), round(max(suncure), 2)), ylab = ylab)
    #   for (i in 2:nx) {
    #     lines(Time, suncure[, i], type = "l", col = i)
    #   }
    #   legend("topright", legend = values, col = 1:nx, lty = 1:nx, title = variable)
    # }
    if (type == "suncure") {
      scm  <- split(suncure, rep(1:ncol(suncure), each = nrow(suncure)))
      for (i in 1:length(scm)) {
        scm[[i]] <- cbind(scm[[i]], Time, num = i)
      }
      scf <- as.data.frame(do.call(rbind, scm))
      colnames(scf) <- c("scm", "Time", "num")
      splot <- ggplot(scf, aes(Time, scm, col = as.factor(num), linetype = as.factor(num))) +
        geom_line() + labs(fill = legendtitle, linetype = legendtitle, col = legendtitle) +
        ylab(ylab)
    }
    if (type == "spop") {
      # p1 <- plot(Time, spop[, 1], type = "l", ylim = c(round(min(spop), 2), round(max(spop), 2)), ylab = ylab, lwd = 2)
      # for (i in 2:nx) {
      #   lines(Time, spop[, i], type = "l", col = i, lwd = 2)
      # }
      # legend("topright", legend = values, col = 1:nx, lty = 1:nx, title = variable)
      spm  <- split(spop, rep(1:ncol(spop), each = nrow(spop)))
      for (i in 1:length(spm)) {
        spm[[i]] <- cbind(spm[[i]], Time, num = i)
      }
      spf <- as.data.frame(do.call(rbind, spm))
      colnames(spf) <- c("spm", "Time", "num")
      splot <- ggplot(spf, aes(Time, spm, col = as.factor(num), linetype = as.factor(num))) +
        geom_line() + labs(fill = legendtitle, linetype = legendtitle, col = legendtitle) +
        ylab(ylab)
    }
  } else {
    mu = c(beta, gamma)
    Coef_smpl <- MASS::mvrnorm(n = nsims, mu = mu, Sigma = cov(diag(mu)))
    Coef_smplb <- Coef_smpl[, 1:length(beta)]
    Coef_smplg <- Coef_smpl[, (length(beta) + 1):ncol(Coef_smpl)]

    # Estimate nsims simulated values of uncureprob
    if (link == "logit") {
      uncureprobsims <- exp(Coef_smplg %*% t(newZ)) / (1 + exp(Coef_smplg %*% t(newZ)))
    }
    if (link == "probit") {
      uncureprobsims <- pnorm(Coef_smplg %*% t(newZ))
    }
    uncuremean = apply(uncureprobsims, 2, mean)
    uncurelo   = apply(uncureprobsims, 2, quantile, 0.05)
    uncurehi   = apply(uncureprobsims, 2, quantile, 0.95)

    # Simulate baseline hazard
    s0sim <- matrix(nrow = nsims, ncol = nobs)
    for (j in 1:nsims) {
      s0sim[j, ] <- as.vector(s0)^exp(Coef_smplb[j, ] %*% t(model$X[, -1]))
    }
    s0mean <- sort(apply(s0sim, 2, mean), decreasing = T)
    s0lo   <- sort(apply(s0sim, 2, quantile, 0.05), decreasing = T)
    s0hi   <- sort(apply(s0sim, 2, quantile, 0.95), decreasing = T)

    # Obtain simulated values of suncure and spop
    ebetaXsim <- exp(Coef_smplb %*% t(newX))
    suncuresims <- array(NA, dim = c(nsims, nobs, nrow(newX)))
    spopsims    <- array(NA, dim = c(nsims, nobs, nrow(newX)))

    for (i in 1:nsims) {
    	# Take the uncureprob for var j and multiply by suncure[j, k]
    	for (j in 1:nobs) {
    		for (k in 1:nrow(newX)) {
    			# spop[i, j] = uncureprobsims[i, j] * suncuresims[i, j] + (1 - uncureprobsims[i, j])
    			suncuresims[i, , k] <- s0sim[i, ]^ebetaXsim[i, k]
    		  spopsims[i, j, k]    <- uncureprobsims[i, k] * suncuresims[i, j, k] + (1 - uncureprobsims[i, k])
    		}
    	}
    }

    suncuremean <- matrix(nrow = nobs, ncol = dim(newZ)) # 284 x 2
    suncurelo   <- matrix(nrow = nobs, ncol = dim(newZ))
    suncurehi  <- matrix(nrow = nobs, ncol = dim(newZ))
    spopmean    <- matrix(nrow = nobs, ncol = dim(newZ))
    spoplo      <- matrix(nrow = nobs, ncol = dim(newZ))
    spophi      <- matrix(nrow = nobs, ncol = dim(newZ))
    for (i in 1:nrow(newX)) {
      suncuremean[, i] <- sort(apply(suncuresims[, , i], 2, mean), decreasing = T)
      suncurelo[, i]   <- sort(apply(suncuresims[, , i], 2, quantile, 0.05), decreasing = T)
      suncurehi[, i]   <- sort(apply(suncuresims[, , i], 2, quantile, 0.95), decreasing = T)
      spopmean[, i]    <- sort(apply(spopsims[, , i], 2, mean), decreasing = T)
      spoplo[, i]      <- sort(apply(spopsims[, , i], 2, quantile, 0.05), decreasing = T)
      spophi[, i]      <- sort(apply(spopsims[, , i], 2, quantile, 0.95), decreasing = T)
    }

    if (type == "uncureprob") {
      # p1 <- plot(values, as.vector(uncuremean),
      #            ylim = c(round(min(uncurelo), 2), round(max(uncurehi), 2)),
      #            xlim = c(0, nx - 1), ylab = "Probability of Failure", axes = F)
      require(plotrix)
      p1 <- plotCI(values, uncuremean, ui = uncurehi[, i], hi = uncurelo[,])
      box()
      axis(1, seq(0, 1, 1))
      axis(2, seq(round(min(uncurelo), 2), round(max(uncurehi), 2), by = ((round(max(uncurelo), 2) - round(min(uncurehi), 2))/2)))
    }
    if (type == "basesurv") {
      # bsm  = split(s0mean, rep(1:ncol(s0mean), each = nrow(s0mean)))
      # bslo = split(s0lo, rep(1:ncol(s0lo), each = nrow(s0lo)))
      # bshi = split(s0hi, rep(1:ncol(s0hi), each = nrow(s0hi)))
      # for (i in 1:length(bsm)) {
      #   bsm[[i]] <- cbind(bsm[[i]], Time, num = i, bslo[[i]], bshi[[i]])
      # }
      # scf <- as.data.frame(do.call(rbind, bsm))
      # colnames(scf) <- c("bsm", "Time", "num", "bslo", "bshi")
      splot <- ggplot(mapping = aes(Time, s0mean)) + geom_line() +
        geom_ribbon(aes(ymin = s0lo, ymax = s0hi), alpha=0.2) + ylab(ylab)
      # p1 <- plot(Time, s0, type = "l",
      #            ylim = c(round(min(s0lo), 2), round(max(s0hi), 2)), ylab = ylab)
      #           lines(s0lo, lty = 2)
    }
    if (type == "suncure") {
      # p1 <- plot(Time, scm[, 1], type = "l", ylim = c(round(min(sclo), 2), round(max(schi), 2)), ylab = ylab)
      # lines(sclo, lty = 2)
      # lines(schi, lty = 2)
      # for (i in 2:nx) {
      #   lines(Time, scm[, i], type = "l", col = i)
      #   lines(sclo[, i], lty = 2, col = i)
      #   lines(schi[, i], lty = 2, col = i)
      # }
      # legend("topright", legend = values, col = 1:nx, lty = 1:nx, title = variable)
      scm  <- split(suncuremean, rep(1:ncol(suncuremean), each = nrow(suncuremean)))
      sclo <- split(suncurelo, rep(1:ncol(suncurelo), each = nrow(suncurelo)))
      schi <- split(suncurehi, rep(1:ncol(suncurehi), each = nrow(suncurehi)))
      for (i in 1:length(scm)) {
        scm[[i]] <- cbind(scm[[i]], Time, num = i, sclo[[i]], schi[[i]])
      }
      scf <- as.data.frame(do.call(rbind, scm))
      colnames(scf) <- c("scm", "Time", "num", "sclo", "schi")
      splot <- ggplot(scf, aes(Time, scm, col = as.factor(num), linetype = as.factor(num))) +
        geom_line() + geom_ribbon(aes(ymin = sclo, ymax = schi, col = as.factor(num),
                                      fill = as.factor(num), linetype = as.factor(num)), alpha=0.2) +
        labs(fill = legendtitle, linetype = legendtitle, col = legendtitle) + ylab(ylab)
    }
    if (type == "spop") {
      # p1 <- plot(Time, spopmean[, 1], type = "l", ylim = c(round(min(spoplo), 2), round(max(spophi), 2)), ylab = ylab, lwd = 2)
      # lines(spoplo, lty = 2)
      # lines(spophi, lty = 2)
      # for (i in 2:nx) {
      #   lines(Time, spopmean[, i], type = "l", col = i, lwd = 2)
      #   lines(spoplo[, i], lty = 2, col = i)
      # }
      # legend("topright", legend = values, col = 1:nx, lty = 1:nx, title = variable)
      spm  <- split(spopmean, rep(1:ncol(spopmean), each = nrow(spopmean)))
      splo <- split(spoplo, rep(1:ncol(spoplo), each = nrow(spoplo)))
      sphi <- split(spophi, rep(1:ncol(spophi), each = nrow(spophi)))
      for (i in 1:length(spm)) {
        spm[[i]] <- cbind(spm[[i]], Time, num = i, splo[[i]], sphi[[i]])
      }
      spf <- as.data.frame(do.call(rbind, spm))
      colnames(spf) <- c("spm", "Time", "num", "splo", "sphi")
      splot <- ggplot(spf, aes(Time, spm, col = as.factor(num), linetype = as.factor(num))) +
        geom_line() + geom_ribbon(aes(ymin = splo, ymax = sphi, col = as.factor(num),
                                      linetype = as.factor(num), fill = as.factor(num)), alpha=0.2) +
        labs(fill = legendtitle, linetype = legendtitle, col = legendtitle) + ylab(ylab)
    }
  }

  if (CI == F) {
    structure(list(uncureprob = uncureprob,
                   s0 = s0, suncure = suncure, spop = spop,
                   Survival = model$Survival,
                   link = link, Time = Time, CI = CI,
                   newX = newX, newZ = newZ, variable = variable, splot = splot),
              class = "predicttvcure")

  } else {
    structure(list(uncuremean = uncuremean, uncurelo = uncurelo, uncurehi = uncurehi,
                   s0mean = s0mean, s0lo = s0lo, s0hi = s0hi,
                   scm = scm, sclo = sclo, schi = schi,
                   spopmean = spopmean, spoplo = spoplo, spophi = spophi,
                   link = link, Time = Time, CI = CI,
                   newX = newX, newz = newZ, variable = variable, splot = splot),
              class = "predicttvcure")
  }
}

# Export uncureprobsims
# TODO Rewrite s0sim a parapply function
# TODO Order singulate s0 in a logical way
# TODO - are graphs behaving for suncure and spop
# Smooth the output of the lines
# Optimize the speed
# choose which fucntion to allow
# create error function if Z and X are not both specified when new
# Create functionality to just get baselines for population
# Make it only spit out an image, not just a summary
